### ISSUE TITLE
Need to declare fields in onCreated

### ISSUE THREAD

**Issue by mordrax** [gwendall/meteor-template-states#1]
1.
Brilliant package, I actually wrote one myself using ReactDict before checking atmosphere again and found yours. Switched mine out for your better implementation. Thank you!

2.
If you're referring to a state in your html and set it in some events, it doesn't react, because I think blaze doesn't know about the ReactiveVar if it's not declared upfront.

i.e you have to declare your states in advance.

```
Template.yourTemplate.onCreated(function () {
    ...
    _.each(['org', 'patient', 'member', 'memberUser'], function (i) {
        self.state(i, null);
    });
    ...
});
```

If this is true, might be worthwhile putting it in the readme.

**Comment by gwendall** [comment]
Thanks! Indeed you have to declare your states in the onCreated hooks - i'll update the doc accordingly.
